name = "Hugo-Theme-Mneme"
license = "The Unlicense"
licenselink = "https://github.com/injellyfish/hugo-theme-mneme/blob/master/LICENSE"
description = "用于中文小说写作的 Hugo 主题"
homepage = "https://injellyfish.github.io/mneme-demo"
tags = ["dark","book"]
features = []
min_version = "0.41.0"

[author]
  name = "injellyfish"
  homepage = "https://github.com/injellyfish"

# If porting an existing theme
[original]
  name = "yihui"
  homepage = "https://github.com/yihui"
  repo = "https://github.com/yihui/hugo-ivy"